### ISSUE TITLE
Implement backpressure test using embedded channel

### ISSUE THREAD

**Issue by artemredkin** [swift-server/async-http-client#117]

**Comment by fabianfett** [comment]
This was done with the recent reimplementation.

https://github.com/swift-server/async-http-client/blob/2bd88855b4e7b9528ab127be7415db48c3f181a4/Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift#L23

https://github.com/swift-server/async-http-client/blob/2bd88855b4e7b9528ab127be7415db48c3f181a4/Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift#L23
