### ISSUE TITLE
Connect timeout defaults to 10 seconds, not indefinite

### ISSUE THREAD

**Issue by djones6** [swift-server/async-http-client#118]
The [documentation for HTTPClient.Configuration.timeout](https://github.com/swift-server/async-http-client/blob/1.0.0-alpha.4/Sources/AsyncHTTPClient/HTTPClient.swift#L321) suggests that the default behavior is not to time out.

However, in practice the client will produce a `NIO.ChannelError.connectTimeout(.nanoseconds(10000000000))` - ie. 10 seconds - by default if the connection is not accepted within that time.

Setting this to a larger (or smaller) value does seem to work however.

**Comment by Lukasa** [comment]
We should probably clean up the documentation. Defaulting to no timeout is a bad idea, IMO, but we should definitely clearly say what the actual behaviour is.
