### ISSUE TITLE
Make URLRequest as a parameter

### ISSUE THREAD

**Issue by seriyvolk83** [swift-server/async-http-client#123]
Why it uses custom class HTTPRequest when there is a perfect URLRequest?

**Comment by seriyvolk83** [comment]
Here it is !124

**Comment by artemredkin** [comment]
2 reasons:
1. it's not uncommon for server-side swift application to not use Foundation, so we don't want our API to depend on Foundation
2. `URLRequest` has additional settings that we cannot support, for example, what if a user sets  something like a `allowsExpensiveNetworkAccess = false` and we don't have a way to actually enforce it? Application might behave unexpectedly for the user.

**Comment by seriyvolk83** [comment]
@artemredkin Got it. 

May be you can help me with the issue I'm facing. I'm implementing  server based on Perfect framework, but when I use other libraries like Alamofire to make HTTP requests from the server to another host the request fails with:
`finished with error - code: -999`
plus
`HTTP load failed (error code: 12 [1:12])`

I think that it's due to disabled arbitrary loads (which usially solved by adding a corresponding properties in Info.plist), but Perfect based code has no .plist and I cannot find the way to fix this.

May be you know the solution? I thought to use this lib instead of Alamofire, but it will require a lot of wrapping code. May be the solution is known for you and simple.

**Comment by artemredkin** [comment]
Sorry, I'm not an iOS developer, and I don't have any experience running Alamofire. Are you using SwiftPM for your server? On the topic of wrappers, you can add an extension to `HTTPClient` in your code using the same code from the PR, that will allow you to use this library if you want.
