### ISSUE TITLE
Do not use SNI when connecting to an IP Address

### ISSUE THREAD

**Issue by StrangeDays** [swift-server/async-http-client#134]
AsyncHTTPClient commit hash: 7aeaf6f0e15d24a64ba9c96d8741faf2e87bf0b6

- Context
Using an IP Address should be allowed but without using SNI. SwiftyRequest is using async-http-client

- Reproduce
`let request = RestRequest(method: .post, url: "https://<ip>:<port>/<path>")`
`request.responseObject( ...`
leads to
`NIOSSL.BoringSSLError.invalidSNIName`

- Relevant Information
https://tools.ietf.org/html/rfc3546
[Slack Thread](https://swift-at-ibm.slack.com/archives/C29BLC4KB/p1574010270043500)

**Suggestion**

- NIOSSLClientHandler.swift (Line: 17)
make `isIPAddress` a public extension (_I like that extension ;-)_)
- HTTPClient.swift (Line 504)
`return self.addHandler(try NIOSSLClientHandler(context: context, serverHostname: request.host.isIPAddress() ? nil : request.host),
                                   position: .first)`

**Comment by weissi** [comment]
CC @artemredkin

**Comment by StrangeDays** [comment]
This bug is fixed
