### ISSUE TITLE
Authorization with async-http-client

### ISSUE THREAD

**Issue by schmidarnold** [swift-server/async-http-client#150]
I am trying to create a request to a server that uses digest authentication, unfortunately without success. I was trying to make a request, then I created from the response header a authorization header and with a new request a sended my authorization header. But I think there is my mistake. I have to send the authorization header  with my first request. Is there a possibility to do this with async-http-client, perhaps in the delegate function ``` func didReceiveHead(task: HTTPClient.Task<Response>, _ head: HTTPResponseHead) -> EventLoopFuture<Void> ``` ... I saw that in the source code there is the possibility of basic authentication... How I have to use it.
Thanks, I know that is not a bug or an issue, but I don't know where to aks such a concrete question.

**Comment by Lukasa** [comment]
You can set arbitrary headers when making your first request by constructing the Request object first. This is probably the best way to do it.

**Comment by schmidarnold** [comment]
But thats not possible with Digest Authentication. I have first to attend the first response from the server and then construct the authorization header. I am searching a way to send a header in an existing request.

**Comment by vkill** [comment]
@schmidarnold 

```
let request = try HTTPClient.Request(url: "/", headers: .init([
    ("authorization", HTTPClient.Authorization.basic(username: "aladdin", password: "opensesame").headerValue)
]))
```

**Comment by vkill** [comment]
> a way to send a header in an existing request

`request.headers.add(name: "foo", value: "bar")`

**Comment by schmidarnold** [comment]
OK, now the digest authentication is running, server gives me response OK. request.headers.add(name:"Authorization", value:computedResponse). I will try to test now to read the data
