### ISSUE TITLE
per-request timeout API is missing

### ISSUE THREAD

**Issue by krzyzanowskim** [swift-server/async-http-client#152]
Timeout described in README: https://github.com/swift-server/async-http-client#timeouts
is (no longer) valid. There's no timeout parameter. 

```
httpClient.execute(request: request, timeout: timeout)
```

Is it still possible to set timeout per request?

**Comment by krzyzanowskim** [comment]
Example needs to be updated to this:

```swift
httpClient.execute(request: request, deadline: .now() + .seconds(3))
```

**Comment by artemredkin** [comment]
fixed, thanks!
