### ISSUE TITLE
There exists a doku about reading the data received from the response?

### ISSUE THREAD

**Issue by schmidarnold** [swift-server/async-http-client#153]
Where can i find information about reading the data from the response. 
``` 
print(response?.body.)
``` 
For example how can I read the jsonData from a server. There exists a function
```
response?.body?.getJSONDecodable(<#T##type: Decodable.Protocol##Decodable.Protocol#>, at: <#T##Int#>, length: <#T##Int#>)
```
My question refers to at and length or there exists a simpler way to read json Data from the server.
Thanks
Arnold

**Comment by Lukasa** [comment]
Try `response.body.readJSONDecodable()` with the length `response.body.readableBytes`.

**Comment by weissi** [comment]
Or

```swift
let jsonDecoder = JSONDecoder()
jsonDecoder.decode(MyType.self, from: response.body)
```

**Comment by schmidarnold** [comment]
Thank you @weissi  and @Lukasa . I will try it out using vapor 4 and this awesome library.
