### ISSUE TITLE
connection pool: idle connection never closed

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#168]
Currently, the pool keeps idle connections open indefinitely (or until the server closes). That is okay from a correctness point of view but may lead to a very large number of open connections when for example implementing a crawler.

**Comment by adtrevor** [comment]
@weissi  Should this be a new global setting on the client that would apply to all of its connections?
Maybe we could set it to an acceptable default value, and if needed expose it as a new `Configuration` property the user can set.
