### ISSUE TITLE
Leaking promise created at ConnectionPool.swift line 373

### ISSUE THREAD

**Issue by fabianfett** [swift-server/async-http-client#179]
Hi,

I just checked out the current master commit `9cdd1dc` and wanted to test it with my [lambda-runtime](https://github.com/fabianfett/swift-lambda-runtime).

When building for macOS in DEBUG, I ran immediately into a fatalError:

```
Fatal error: leaking promise created at (file: "/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-brfbdomqotikxpeqafasrajmegus/SourcePackages/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool.swift", line: 373): file /Users/xxx/Library/Developer/Xcode/DerivedData/xxx-brfbdomqotikxpeqafasrajmegus/SourcePackages/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool.swift, line 373
```

This happens on the first invocation of `execute`.

I haven't found a similar issue here, so that's why I created one.

**Comment by Lukasa** [comment]
Hmm, this error could well be caused by a path where promises can be leaked if creating `NIOSSLContext` objects fail. Specifically:

https://github.com/swift-server/async-http-client/blob/9cdd1dc38998fc34c0a99f481ad60e0bc43d5888/Sources/AsyncHTTPClient/HTTPClient.swift#L634-L645

`handshakePromise` is passed to `TLSEventsHandler` here, but if the line above throws then it'll be leaked.

**Comment by Lukasa** [comment]
(The same logic applies to the return value of `self.addHandlers` which can also leak this promise if the returned future fails)

**Comment by fabianfett** [comment]
@Lukasa For reference I create a connection to `http://localhost:7000`.

**Comment by Lukasa** [comment]
Heh, yup, that promise can _also_ be leaked if the connection attempt fails.

**Comment by Lukasa** [comment]
Lots of ways to leak that promise it seems.

**Comment by fabianfett** [comment]
Okay, besides the fact, that we shouldn't leak I found the issue, why it was happening to me. I tried to connect to `http://http://127.0.0.1:7000`. So I guess dns failed?

**Comment by Lukasa** [comment]
Yup, that sounds right.

**Comment by weissi** [comment]
CC @adtrevor

**Comment by adtrevor** [comment]
@fabianfett Thank you for reporting the issue, #180 should fix it 🙂 
cc: @Lukasa @weissi
