### ISSUE TITLE
Redundant Naming

### ISSUE THREAD

**Issue by calebkleveter** [swift-server/async-http-client#18]
The name for this repo is rather redundant. Because the org is called `swift-server`, it can be safely assumed that Swift is the language that the projects will be built in. I suggest that the `swift-` prefix gets removed from the repo name. This makes the names more concise.

There are a couple of reasons I can think of that people might have against this, and why I think they aren't issues:

- Discoverability: GitHub already handles this for us, by marking each repo with the language it is primarily written in.
- Apple uses it: The Apple org also has repos that use other languages, such as C and C++. Swift Server is purely Swift.

**Comment by weissi** [comment]
+1 from me.

**Comment by Lukasa** [comment]
-1 from me: the repo name affects the default directory name when cloning the repo, and in that context swift-server will not be present.

**Comment by weissi** [comment]
> -1 from me: the repo name affects the default directory name when cloning the repo, and in that context swift-server will not be present.

Sure, but why do you need to know it's written in Swift? It's also not `swift-kitura`/`swift-vapor`, right? Tbh I don't even think we need the `nio` bit.

**Comment by tanner0101** [comment]
Both URL and package name are `nio-*`:
```
https://github.com/vapor/nio-postgres
https://github.com/vapor/nio-mysql
https://github.com/vapor/nio-sqlite
https://github.com/vapor/nio-websocket-client
https://github.com/mordil/nio-redis
```

URL prefixed with `swift-nio-*` but package is `nio-*`

```
https://github.com/kylebrowning/swift-nio-apns
```

URL and package name prefixed with `swift-nio-*`

```
https://github.com/apple/swift-nio-ssl
https://github.com/apple/swift-nio-http2
```

**Comment by weissi** [comment]
@tanner0101 very good point. In SwiftPM, there are three identifiers that need to be unique _across the whole dependency tree_ for any given application:

- URL basename (i.e. the `swift-nio` in `https://github.com/apple/swift-nio`)
- the package name in the `Package.swift` (e.g. `let package = Package(name: "swift-nio", ...)`)
- module names (e.g. `NIO`)

so we should always thing about them. So far the SSWG packages are consistent:

- NIO: URL: `swift-nio[-*]`, package: `swift-nio[-*]`, modules: `NIO*`
- SwiftLog: URL: `swift-log`, package: `swift-log`, module: `Logging`
- SwiftMetrics: URL: `swift-metrics`, package: `swift-metrics`, module: `Metrics`

**Comment by weissi** [comment]
CC @artemredkin / @tomerd / @ktoso / @yimlee

**Comment by artemredkin** [comment]
I'm in favour of dropping swift-*, but only if it's consistent across other libraries. I don't mind having two `swift`s in my package URL at all, but would prefer for `swift-` to be dropped everywhere (if it's feasible).

**Comment by yim-lee** [comment]
I think it's good to know the underlying framework (i.e., SwiftNIO) by just looking at the repo name, so definitely prefer `swift-server/swift-nio-http-client` or `swift-server/nio-http-client`. 

I don't mind having two `swift`s either because "swift-nio" seems more proper to me--similar to "John Smith" vs. "John"--"swift" is like a surname.

**Comment by tomerd** [comment]
`swift-server/swift-nio-http-client` or `swift-server/nio-http-client` both sound good to me. we originally named this `swift-nio-http-client` to follow the pattern established with `swift-nio`, `swift-log` and `swift-metrics`. the `swift` prefix for these three stems from the fact they are in the `apple` org that contains other technologies as well, so we needed to be able to know that they are swift packages at a glance

**Comment by ianpartridge** [comment]
My preference would be `swift-` everywhere - I don't think it does any harm and it makes all my GitHub checkouts appear next to each other.  But we may not be able to achieve that consistency given the divergent views here :-)

There's also the issue of the `-client` suffix. We have `nio-websocket-client` (cool to see that @tanner0101!) but `nio-redis`. I'd prefer the latter to be `nio-redis-client` (or `swift-nio-redis-client`) personally.

**Comment by tomerd** [comment]
in my experience explicit naming is typically better

**Comment by weissi** [comment]
https://forums.swift.org/t/namespacing-of-packages-modules-especially-regarding-swiftnio/24726

**Comment by artemredkin** [comment]
Since project was renamed to `async-http-client` I think this issue is no longer relevant.
