### ISSUE TITLE
programming model:`task.futureResult` not bound to desired EL if `.delegate(on:)` is specified

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#199]
Again, I'm not 100% sure if this counts as a bug but I think it should. If I set my `EventLoopPreference` to `.delegate(on: desiredEL)`, then I probably want everything to happen on `desiredEL`.

I would argue that all the user-visible things that are important for the programming model should then happen on `desiredEL`. Mainly:

- all delegate methods (true today)
- `task.futureResult` (not true today)
- the closure that gets me the `StreamWriter` (not true today, #198)

**Comment by weissi** [comment]
Same comment as on #200:

> After a chat with @ktoso, I noticed that this ticket isn't clear enough. The rules should be:
>
> All callouts (delegate, futures, callbacks, ...) AHC makes to the user should be on the preferred EL, no matter where the Channel lives
All callins (returned futures, callins, ...) from the user must be tolerated on any thread.
IMHO fixing this issue is blocking 1.2.0, we cannot possibly release it as on master as it's impossible to use right now.

**Comment by ktoso** [comment]
I started looking into this a bit btw, may have more time soon to continue on it.
