### ISSUE TITLE
StreamWriter expects to be called on some internal EventLoop

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#200]
The `HTTPClient.Body.StreamWriter` that you get when using the default `.stream(length: contentLength, { thisStreamWriterHere in })` expects to be called on the internal `EventLoop` that belongs to the underlying `Channel`. The user however doesn't get access to that `Channel` at all so it's impossible to use this API :(.

This needs a fix really soon.

**Comment by weissi** [comment]
After a chat with @ktoso, I noticed that this ticket isn't clear enough. The rules should be:

- All callouts (delegate, futures, callbacks, ...) AHC makes _to_ the user should be on the preferred EL, no matter where the `Channel` lives
- All callins (returned futures, callins, ...) _from_ the user must be tolerated on any thread.

IMHO fixing this issue is blocking 1.2.0, we cannot possibly release it as on `master` as it's impossible to use right now.

**Comment by ktoso** [comment]
I started looking into this a bit btw, may have more time soon to dedicate to this.

**Comment by artemredkin** [comment]
It seems that this is more about API, than a programming model, no? Even if I fix #192 in #215 , it will still not solve this issue if I don't want to specify task EL myself, right?

**Comment by weissi** [comment]
@artemredkin Not sure, the `write` API for `StreamWriter` can stay as is but it can't make the assumption it makes today because that makes it impossible to use with the connection pool.
In theory, we could mandate that the user calls us back on the delegate's EL but that would be of no benefit to us because we need to hop EL's to the Channel's EL anyway so we should just accept callins on any EL.

**Comment by weissi** [comment]
when this gets fixed, we also need to undo this hack: https://github.com/swift-server/async-http-client/pull/219/files#diff-bd03a2521c79f3da4bd5825512ca9979R1739-R1741
