### ISSUE TITLE
connectTimeout(NIO.TimeAmount(nanoseconds: 10000000000))

### ISSUE THREAD

**Issue by VineFiner** [swift-server/async-http-client#204]
very simple code

```
    func normalRequest() {
        if let url = URL(string: "https://www.google.com") {
            let info = try? String(contentsOf: url)
           // can print
            print(info?.count ?? "")
        }
       // timeout
        let httpClient = HTTPClient(eventLoopGroupProvider: .createNew)
        let request = try! HTTPClient.Request(url: "https://www.google.com/", method: .GET)
        let task: EventLoopFuture<HTTPClient.Response> = httpClient.execute(request: request)
        task.whenComplete { result in
            switch result {
            case .failure(let error):
                // process error
                print(error)
            case .success(let response):
                if response.status == .ok {
                    // handle response
                    print(response)
                } else {
                    // handle remote error
                    print(response)
                }
            }
        }
    }
```

output

```
Optional(13152)

connectTimeout(NIO.TimeAmount(nanoseconds: 10000000000))
```

**Comment by artemredkin** [comment]
what OS are you running this code on? Have tried increasing the timeout just to see if it works?

**Comment by VineFiner** [comment]
> what OS are you running this code on? Have tried increasing the timeout just to see if it works?

mac os 10.15.4

xcode 11.4

use v2ray Forwarding network

I recreated the app. The complete code is as follows

```
import AsyncHTTPClient
import NIO
import Foundation

print("Hello, world!")

let timeout = HTTPClient.Configuration.Timeout(connect: .seconds(1), read: .seconds(1))
let httpClient = HTTPClient(eventLoopGroupProvider: .createNew,
                            configuration: HTTPClient.Configuration(timeout: timeout))
if let url = URL(string: "https://www.google.com") {
    let info = try? String(contentsOf: url)
    // can print
    print("content result:\(String(describing: info?.count))\n")
}
let request = try! HTTPClient.Request(url: "https://www.google.com/", method: .GET)
let task: EventLoopFuture<HTTPClient.Response> = httpClient.execute(request: request)
let response = try! task.wait()

print(response)

print("end")
```

# error Info

```
Hello, world!
content result:Optional(13199)

Fatal error: 'try!' expression unexpectedly raised an error: NIO.ChannelError.connectTimeout(NIO.TimeAmount(nanoseconds: 1000000000)): file /Volumes/Additional/Developer/SwiftServer/testasync/Sources/testasync/main.swift, line 17
2020-04-24 09:24:29.414794+0800 testasync[3125:30673] Fatal error: 'try!' expression unexpectedly raised an error: NIO.ChannelError.connectTimeout(NIO.TimeAmount(nanoseconds: 1000000000)): file /Volumes/Additional/Developer/SwiftServer/testasync/Sources/testasync/main.swift, line 17
(lldb) 
```

**Comment by artemredkin** [comment]
After reading about v2ray I'm inclined to think that it's the cause of issue. I don't have any experience with it, so I'll need you help figuring this one out. Could you please send output of:
```
curl -vvv --http1.1 https://google.com
```
?

**Comment by VineFiner** [comment]
> 阅读有关v2ray的文章后，我倾向于认为这是问题的根源。我没有任何经验，所以我需要您帮助弄清楚这一点。您能否发送以下内容的输出：
> 
> ```
> curl -vvv --http1.1 https://google.com
> ```
> 
> ？

➜  ~ curl -vvv --http1.1 https://google.com
* Uses proxy env variable https_proxy == 'http://127.0.0.1:1087'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 1087 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to google.com:443
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.64.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.google.com
*  start date: Apr  1 12:50:35 2020 GMT
*  expire date: Jun 24 12:50:35 2020 GMT
*  subjectAltName: host "google.com" matched cert's "google.com"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Sun, 26 Apr 2020 11:22:00 GMT
< Expires: Tue, 26 May 2020 11:22:00 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 220
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0

**Comment by VineFiner** [comment]
> After reading about v2ray I'm inclined to think that it's the cause of issue. I don't have any experience with it, so I'll need you help figuring this one out. Could you please send output of:
> 
> ```
> curl -vvv --http1.1 https://google.com
> ```
> 
> ?

➜  ~ curl -vvv --http1.1 https://www.google.com
* Uses proxy env variable https_proxy == 'http://127.0.0.1:1087'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 1087 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.64.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=www.google.com
*  start date: Apr  1 12:58:56 2020 GMT
*  expire date: Jun 24 12:58:56 2020 GMT
*  subjectAltName: host "www.google.com" matched cert's "www.google.com"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sun, 26 Apr 2020 11:23:06 GMT
< Expires: -1
< Cache-Control: private, max-age=0
< Content-Type: text/html; charset=ISO-8859-1
< P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< Server: gws
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: 1P_JAR=2020-04-26-11; expires=Tue, 26-May-2020 11:23:06 GMT; path=/; domain=.google.com; Secure
< Set-Cookie: NID=203=uoOmUx1hcHIRA6KubkT6Bhf2upsvamPdynxoFzA7OtdGUZSJP58pffuqp6lzE7pqhXGYqHt3KPYiY4CgUygKiRBNXopqJt0UrE3yrt5-GTmIhHyBRlEUa5mL3lruu8IsadcrykCWZ2urvtF5SNlIqP1aqJRuYqmEF6sVU7XvYpc; expires=Mon, 26-Oct-2020 11:23:06 GMT; path=/; domain=.google.com; HttpOnly
< Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
< Accept-Ranges: none
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
<!doctype html>....        </body></html>* Closing connection 0
➜  ~

**Comment by artemredkin** [comment]
Could you try modifying your client configuration to:
```
let httpClient = HTTPClient(eventLoopGroupProvider: .createNew,
                            configuration: .init(
                                timeout: timeout,
                                proxy: .server(host: "localhost", port: 1087)
                            ))
```
and test if it works?

**Comment by VineFiner** [comment]
> Could you try modifying your client configuration to:
> 
> ```
> let httpClient = HTTPClient(eventLoopGroupProvider: .createNew,
>                             configuration: .init(
>                                 timeout: timeout,
>                                 proxy: .server(host: "localhost", port: 1087)
>                             ))
> ```
> 
> and test if it works?

Okay, he can work normally. thank you very much.
But why does URLSession need no additional configuration?

**Comment by artemredkin** [comment]
I think `URLSession` uses the same environmental variable as `curl`.

**Comment by artemredkin** [comment]
See first line in your `curl` output:
```
Uses proxy env variable https_proxy == 'http://127.0.0.1:1087'
```

**Comment by weissi** [comment]
> I think `URLSession` uses the same environmental variable as `curl`.

I reckon `URLSession` actually uses the system's configured proxy in Network Preferences. Those might also get exported as environment variables. Possibly the system's curl is also reading directly from the network settings.
