### ISSUE TITLE
"chunked" upload does not add length at the start of each chunk

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/async-http-client#212]
When uploading chunked data each chunk needs to be preceded by the size of the chunk in hexadecimal and then the characters "\r\n" and the chunk is terminated with "\r\n". Currently AHC does not do this. Is this expected to be the left to the user to implement this?

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

**Comment by weissi** [comment]
@adam-fowler wait, NIO does that already. We didn't have that many tests around it but I wrote some in this PR: https://github.com/apple/swift-nio/pull/1524

This seems to work fine.

**Comment by weissi** [comment]
(I did find an unrelated bug which I did fix)

**Comment by weissi** [comment]
@adam-fowler do you have a reproduction program that shows the issue?

**Comment by adam-fowler** [comment]
> @adam-fowler wait, NIO does that already. We didn't have that many tests around it but I wrote some in this PR: [apple/swift-nio#1524](https://github.com/apple/swift-nio/pull/1524)
> 
> This seems to work fine.

Let me verify the issue, The verification will be in the middle of aws-sdk-swift-client code at the moment. I can probably extract it. Would the NIOHTTP1TestServer read the chunk headers, if I want to verify it is working?

**Comment by weissi** [comment]
@adam-fowler `NIOHTTP1TestServer`'s `/dynamic/echo_balloon` route will echo the body bytes back to you. So let's say you write write `.body("foo)"`, `.body("bar")`, `.body("buz")`, thien `NIOHTTP1TestServer` should reply back `foobarbuz`.

Example:

```
$ echo -e 'POST /dynamic/echo_balloon HTTP/1.1\r\ntransfer-encoding: chunked\r\n\r\n3\r\nfoo\r\n3\r\nbar\r\n0\r\n\r\n' | nc localhost 8888
HTTP/1.1 200 OK
Content-Length: 6

foobar
```

**Comment by adam-fowler** [comment]
Sorry @weissi I'm wasting your time. Looks like I was mistaken. I've ended up implementing another set of markers inside the ones NIO generates. Not sure how I got here :-/
