### ISSUE TITLE
New release for 1.1.2/1.2.0

### ISSUE THREAD

**Issue by iainsmith** [swift-server/async-http-client#213]
Hi All,

It would be great to cut a new release that includes the latest bug fixes and changes if possible. Here's a link to [compare/1.1.1...master](https://github.com/swift-server/async-http-client/compare/1.1.1...master)

**Comment by artemredkin** [comment]
There are some blockers for the `1.2.0` release:
https://github.com/swift-server/async-http-client/issues?q=is%3Aopen+is%3Aissue+label%3A%22⚠%EF%B8%8F+release+blocker%22
And we need https://github.com/swift-server/async-http-client/pull/192 before we can tag
As soon as those fixed land, we will cut a new release

**Comment by artemredkin** [comment]
It is also a good idea to keep an eye on our `1.2.0` milestone:
https://github.com/swift-server/async-http-client/milestone/3

**Comment by iainsmith** [comment]
> It is also a good idea to keep an eye on our `1.2.0` milestone:
> https://github.com/swift-server/async-http-client/milestone/3

Thanks @artemredkin. I'd missed that we are using milestones on this project.

**Comment by weissi** [comment]
I'm closing this. 1.2.0 _will happen_ (once the release blockers are done).
