### ISSUE TITLE
If not given a content-length, .stream should assume transfer-encoding:chunked

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#218]
[THIS SHOULD BE FIXED AFTER #217]

```
        let request = try! HTTPClient.Request(url: "http://localhost:\(httpBin.port)/get",
                                              method: .POST,
                                              body: .stream { streamWriter in
```

this `Request` will actually error (sort of, see #217) but it should just assume `transfer-encoding: chunked`, the user clearly hasn't given a content length.

If the user manually set a `content-length` in `headers:`, then we should obvs use that.

**Comment by artemredkin** [comment]
@weissi do you think we need to prepend length to bytes we get from the client? Or just assume that the client did that?

**Comment by weissi** [comment]
> @weissi do you think we need to prepend length to bytes we get from the client? Or just assume that the client did that?

I don’t quite understand the question. What do you want to prepend?

**Comment by artemredkin** [comment]
@weissi length of the chunk being written, followed by `\r\n`

**Comment by weissi** [comment]
@artemredkin that is the HTTP wire protocol. And neither AHC nor the user should think about it. NIO does the HTTP wire protocol (incl chunked encoding) for you. If yoy were to prepend anything in AHC then that would go into the data stream so it would become corrupted.

From AHC’s perspective, you don’t need to worry about chunked or not. You can select it by:

- add no headers: NIO will assume chunked encoding
- explicitly add `transfer-encoding: chunked`, NIO ofc will do chunked
- add a `content-length` header in which case NIO will not do chunked ofc

**Comment by weissi** [comment]
@artemredkin a few things that AHC does need to do are:
- make sure there’s no `content-length` and `transfer-encoding: chunked` headers at the same time, that’s illegal
- if `content-length` is selected, AHC must make sure that the user is actually supplying exactly that many bytes and no more/less

**Comment by artemredkin** [comment]
Ok, got it, thanks! I’ll address body checking when I get to #251
