### ISSUE TITLE
AHC seems to return from its `syncClose` before it's actually done

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#220]
When running `testUploadsReallyStream` from #219, I often get this message printed to the command line:

```
ERROR: Cannot schedule tasks on an EventLoop that has already shut down. This will be upgraded to a forced crash in future SwiftNIO versions.
```

But I do wait for everything to shut down.

I suspect that AHC isn't actually 100% done after its `syncShutdown` method returns. There might be some still active `Channel`s? Unsure, but there's definitely a bug in either AHC or NIO.

NIO issues this printout (will be upgraded to crash in the future), if the ELG has been shutdown and after that has happened, more work gets scheduled (which is illegal because it can never run).

**Comment by artemredkin** [comment]
Closed by #221
