### ISSUE TITLE
It's likely redirects for sockets and regular hosts never behaved as expected

### ISSUE THREAD

**Issue by dimitribouniol** [swift-server/async-http-client#230]
While refactoring the unix domain socket implementation in #228, I noticed that redirects likely haven't been checking URL schemes correctly for some time now, or I'm not completely following the logic and intended use of `RedirectHandler`.

My _assumption_ is that `RedirectHandler.redirectTarget(status:, headers:)` validates the incoming header, and returns a URL to redirect to if it passes all the necessary checks.

If I'm right, that means that the redirect logic checks the current request rather than the new URL to see if it can redirect to it - this likely never worked as designed due to the fact that it would always pass, since we have a request that is already valid, and we are checking it once again for validity...

It's also likely that this check never worked, but redirects to foreign URLs were still possible, since creating the Request later in the process would eventually fail, but there are no checks to ensure the Request hasn't been redirected from a host-based server to a socket based one, so something is still fishy in that regard.

If my assumption isn't misguided in some way, I suggest we refactor the check for the scheme as follows:
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/225505/83043339-98f2aa00-9ff7-11ea-9e41-3506b9712e99.png">

The new `supportsRedirects(to:)` method (refactored, since it is only being used in this scenario now):
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/225505/83043233-752f6400-9ff7-11ea-9f5a-aa71c90bf962.png">

Additional tests should clarify if this is working as designed or not.

**Comment by Lukasa** [comment]
Yup, this looks like the correct diagnosis. It'd be really good to add a test for this to verify that the behaviour really is wrong, and then apply the fix.

**Comment by dimitribouniol** [comment]
@Lukasa I finally got around to writing tests for the above, which definitely do fail:
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/225505/84579494-fa01d800-ad82-11ea-9984-3f88bed37d3f.png">

The second half (which currently passes) is to ensure the other scenarios (`http(s)+unix` to `http(s)`/`http(s)+unix`) all continue to work.
https://github.com/swift-server/async-http-client/compare/master...dimitribouniol:redirect-validation

Any other concerns with this approach, or should I open a PR with the fix?

**Comment by Lukasa** [comment]
No concerns from me, this approach looks reasonable.
