### ISSUE TITLE
add test for error condition in line 151 of ConnectionsState.swift

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#244]
@artemredkin from what I can tell, no test noticed that this error changed which probably means no test is getting this error ;). I think we should probably add a test case that tests this condition.

_Originally posted by @weissi in https://github.com/swift-server/async-http-client/pull/240_

**Comment by weissi** [comment]
https://github.com/swift-server/async-http-client/pull/240/files#diff-bfea29858f72f0aa5df7309d1123b672R151

**Comment by fabianfett** [comment]
No longer needed, since the implementation was completely replaced.
