### ISSUE TITLE
How can i get request body?

### ISSUE THREAD

**Issue by Adrift001** [swift-server/async-http-client#281]
I can't find a method to get request body. Can anyone help me?

**Comment by Lukasa** [comment]
`HTTPClient.Request.body` is where the request body will be stored.

Can you provide an example of your code where you'd like access to the request body?

**Comment by Adrift001** [comment]
```
public final class AuthorizationPlugin: PluginType {
    public func prepare(_ request: Request, target: TargetType) -> Request {
        var request = request
        let method = request.method
        let path = request.url.path
        let query = request.url.query == nil ? "" : "?\(request.url.query ?? "")"
        let host = request.host
        let contentType = request.headers["Content-Type"].first ?? ""
        
        #warning("Can't get request body")
        let signingStr = """
        \(method) \(path)\(query)
        Host: \(host)
        Content-Type: \(contentType)
        Body: body

        """
        request.headers.add(name: "Authorization", value: "Qiniu \(Auth.accessToken(signingStr: signingStr))")
        return request
    }
}
```
I need body data for generating token.

**Comment by Lukasa** [comment]
Body data will be available at `request.body`.

**Comment by Adrift001** [comment]
OK, thanks

**Comment by Adrift001** [comment]
How can i convert body to String?

**Comment by Lukasa** [comment]
`body.readString(length: body.readableBytes)`.

**Comment by Adrift001** [comment]
I want convert Request.Body to String, not Response Response Body.
Request Body don't have this method.

**Comment by Lukasa** [comment]
Oh, I'm sorry.

This is not straightforward. Because `Request.Body` may be streamed, it is not trivial to convert it to a `String`. What do you need the `String` for?

**Comment by Adrift001** [comment]
![image](https://user-images.githubusercontent.com/8119320/86898918-e22c3280-c13b-11ea-86e7-5fa382be55d1.png)
I need body string to generate authorization token

**Comment by Lukasa** [comment]
Ok, so the only way to achieve this in full generality will be to consume the entire request body. Note that this may potentially invalidate the request, so you should _also_ overwrite the request body.

To consume the request body you can do something like this:

```swift
import NIO
import AsyncHTTPClient

extension HTTPClient.Body {
    func consume(on loop: EventLoop) -> EventLoopFuture<String> {
        var string = ""
        let streamWriter = StreamWriter { data in
            switch data {
            case .fileRegion:
                preconditionFailure("not supporting reading from files today")
            case .byteBuffer(var data):
                string += data.readString(length: data.readableBytes)!
                return loop.makeSucceededFuture(())
            }
        }

        return self.stream(streamWriter).map { string }
    }
}
```

Note that this is a potentially destructive operation: nothing guarantees that streams can be replayed. This means your code will also need to create a new body using `HTTPClient.Body.string` with the returned string.

**Comment by Adrift001** [comment]
OK, thank!
