### ISSUE TITLE
Sharing an HTTPClient in AWSLambda

### ISSUE THREAD

**Issue by leogdion** [swift-server/async-http-client#325]
Is there any recommendations regarding maintaining an AWSClient (from Soto) and an HTTPClient from AsyncHttpClient with a Lambda? I’m using a Singleton Application to store each. However I am continually getting:

```
0x55b0dc3c3c8d, Swift runtime failure: precondition failure at /src/.build/checkouts/async-http-client/Sources/AsyncHTTPClient/HTTPClient.swift:0
```

Which I believe come from one of the preconditions here:

```
        case .delegate(on: let eventLoop):
            precondition(self.eventLoopGroup.makeIterator().contains { $0 === eventLoop }, "Provided EventLoop must be part of clients EventLoopGroup.")
            taskEL = eventLoop
        case .delegateAndChannel(on: let eventLoop):
            precondition(self.eventLoopGroup.makeIterator().contains { $0 === eventLoop }, "Provided EventLoop must be part of clients EventLoopGroup.")
            taskEL = eventLoop
```

I’m trying to replicate the suggested mechanism which Soto recommends for Vapor 4 in the Lambda so I have an Application class with these props:

```
  public lazy var eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: self.configuration.numberOfThreads)
  public lazy var httpClient: HTTPClient = {
    AsyncHTTPClient.HTTPClient(eventLoopGroupProvider: .shared(self.eventLoopGroup))
  }()
  public lazy var awsClient: AWSClient = {
    let credentialProvider: CredentialProviderFactory
    credentialProvider = self.configuration.aws.access.map(CredentialProviderFactory.static) ?? .default
    return AWSClient(credentialProvider: credentialProvider, httpClientProvider: .shared(self.httpClient))
  }()
```

then in main.swift:

```
Application.shared.run(ApplicationHandler())
```

**Comment by Lukasa** [comment]
If one of those preconditions are firing, it suggests that the call site is requesting a specific event loop for use with the request, and that event loop isn’t in the ELG you configured the HTTP client with. Do you have a full traceback?

**Comment by leogdion** [comment]
Hey @Lukasa this can be closed. Once I realized there was an instance of `Lambda.run` which  takes a factory with the `InitializationContext` (containing the `EventLoop`) I was good.
Thank you
