### ISSUE TITLE
Docs are wildly out of date

### ISSUE THREAD

**Issue by Lukasa** [swift-server/async-http-client#331]
Seems like the documentation hasn't been updated since February 2020. @tomerd it's likely a Jenkins job is busted, can you take a look?

**Comment by Lukasa** [comment]
Docs link: https://swift-server.github.io/async-http-client/docs/current/AsyncHTTPClient/index.html

Footer: 
<img width="509" alt="Screenshot 2021-01-19 at 17 24 00" src="https://user-images.githubusercontent.com/1382556/105070394-213c2880-5a7b-11eb-816f-948955bc4f31.png">

**Comment by tomerd** [comment]
looks like that build is broken, will look into it

**Comment by tomerd** [comment]
confirm that `main` now has a working script, and generated latest docs for it. next tag should work as expected
