### ISSUE TITLE
Question:  HTTPClient request when I'm already on an EventLoop

### ISSUE THREAD

**Issue by winsmith** [swift-server/async-http-client#340]
I use Vapor, and for some specific requests, I need to query another server over HTTP before being able to answer a HTTP request.

Since Vapor is based on SwiftNIO, I heeded the second warning about not spawning new threads but instead using `eventLoopGroupProvider: .shared(myExistingEventLoopGroup)`. This is how my code looks like:

```swift
let httpClient = HTTPClient(eventLoopGroupProvider: .shared(req.application.eventLoopGroup.next()))
defer { try? httpClient.syncShutdown() }

var request = try! HTTPClient.Request(url: queryAPIURL, method: .POST)
request.body = .string(query)

httpClient.execute(request: request)
// Vapor expects that route closures will stay on req.eventLoop, so let's hop back to it
.hop(to: req.eventLoop)
.map { result in
    return "some result"
}
```

My problem now is this: If I use the defer statement in line 2 of the code snippet, I get a crash with this error: `NIO-ELT-0-#10 (12): Fatal error: BUG DETECTED: syncShutdown() must not be called when on an EventLoop.`

So, okay, I think, maybe the syncShutdown stuff doesn't apply to me. However, when I comment out line 2, I get a crash with `Assertion failed: file AsyncHTTPClient/HTTPClient.swift, line 117`. Line 117 in HTTPClient.swift is this:

```swift
deinit {
    assert(self.pool.count == 0) // <- crash here
    assert(self.state == .shutDown, "Client not shut down before the deinit. Please call client.syncShutdown() when no longer needed.")
}
```

Obviously, pool count is not 0 since I never called syncShutdown. But I don't know how to call that since I get a crash when I do. I'm at a loss here. Can you help me? 

- What's the correct way to run a HTTPClient request when I'm already on an EventLoop? 
- How do I deal with syncShutdown when using Vapor/SwiftNIO?

**Comment by t089** [comment]
Don't call `syncShutdown`, call the async variant: `httpClient.shutdown() { _ in }`

But maybe you only want to call this after your request has completed.

Also you can avoid the `hop` be providing already the request event loop: 

```swift
HTTPClient(eventLoopGroupProvider: .shared(req.eventLoop))
```

Additionally, I think the Vapor application already comes with a preconfigured "shared" HTTPClient you can use.

**Comment by winsmith** [comment]
Ooh thank you! I have just found the built-in HTTPClient, I don't know how I could have missed that. The shutdown concept is hard for me to get into somehow 😅
