### ISSUE TITLE
make `maximumConcurrentConnections` configurable

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#373]
- `maximumConcurrentConnections` is an important property for any system using AHC, it therefore should really be configurable
- 8 seems also very low

Technically, the introduction of the "max 8 connections at a time" can be seen as API breaking in AHC version 1.1.0. There are certainly programs that worked correctly with AHC 1.0.0 (without the pool) and then broke with 1.1.0 which limited the number of concurrent connections to 8.

**Comment by weissi** [comment]
cf rdar://79360051

**Comment by Lukasa** [comment]
Agreed that `maximumConcurrentConnections` should be configurable. The default of 8 is in the ballpark of typical browsers (which tend to land at 6) and seems like a reasonable default for many use-cases, but it should definitely be overridable.

**Comment by weissi** [comment]
@Lukasa well, isn't the browser limit 6 per tab?

**Comment by Lukasa** [comment]
Yes, it's 6 per origin. So far as I can see in the AHC code the 8 limit is also per origin: it's in the `HTTP1ConnectionProvider`, which is one-per-origin.

**Comment by weissi** [comment]
@Lukasa I think you're right, thank you! Okay, in that case let's call 8 a good default but we should make it configurable.

**Comment by Lukasa** [comment]
@fabianfett As you're doing a substantial rework of the pool, want to factor this in? May be worth making this change once on mainline because it should be straightforward, but making sure the API can fold nicely into your work.

**Comment by weissi** [comment]
@fabianfett I think this needs to be moved to the 1.6.0 milestone, correct?
