### ISSUE TITLE
Fire `didTransmitRequestBody` only when write future is filfilled

### ISSUE THREAD

**Issue by artemredkin** [swift-server/async-http-client#38]

**Comment by adtrevor** [comment]
Should this event be sent once `body` has been transmitted but before `end`, or should it be sent after both have been transmitted?

**Comment by Lukasa** [comment]
After both. In most cases `.end` produces a zero-length write which is trivially succeeded, but in some cases it produces actual bytes that must reach the wire.

**Comment by artemredkin** [comment]
Yes, after both. Right now semantic of this callback is that `request is sent`.

**Comment by artemredkin** [comment]
Fixed by #65
