### ISSUE TITLE
AHC may crash if an read idle timeout is set, but a running request fails before receiving http .end

### ISSUE THREAD

**Issue by fabianfett** [swift-server/async-http-client#453]
Currently we only clear the idle read timer, if we receive an http `.end`. 

https://github.com/swift-server/async-http-client/blob/a0b09857d898420fcacfcc73cb4906c9f26b4203/Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ClientChannelHandler.swift#L468

However if the request is cancelled or the connection fails, we may never receive such an event. For this reason we should ensure in 

https://github.com/swift-server/async-http-client/blob/a0b09857d898420fcacfcc73cb4906c9f26b4203/Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ClientChannelHandler.swift#L34-L35

with a `willSet` method that a running idleReadTimeoutTimer is cancelled. Currently we may run into a precondition if:

Currently we should run into a precondition, if the following happens:

1. On an HTTPClient that has idleTimeout enabled a request is sent
2. The remote server waits to receive the full request and closes the connection without sending a response
3. The HTTPClient and its ELG must be kept alive for at least the idleTimeout duration

We should run into the precondition here:

https://github.com/swift-server/async-http-client/blob/a0b09857d898420fcacfcc73cb4906c9f26b4203/Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift#L311

**Comment by dnadoba** [comment]
Fixed in #455 and [released with 1.6.2](https://github.com/swift-server/async-http-client/releases/tag/1.6.2)
