### ISSUE TITLE
Licence is invalid

### ISSUE THREAD

**Issue by 0xTim** [swift-server/async-http-client#523]
The Apache licence added to the project does not contain a copyright year or name of the copyright holder - https://github.com/swift-server/async-http-client/blob/main/LICENSE.txt#L190

This should probably be fixed...

**Comment by fabianfett** [comment]
cc @tomerd

**Comment by Lukasa** [comment]
We don't need @tomerd's help here, we can just update that file. Incidentally I don't believe that it renders the license invalid in any way, it's just a bit less convenient to copy into forks.

**Comment by 0xTim** [comment]
Who's the code owner here? Swift, Apple or the SSWG? I'm only asking as we need to add a licence for the VSCode extension which is how I stumbled upon this

**Comment by weissi** [comment]
@0xTim I think the `LICENSE.txt` file is actually supposed to have the placeholders.

The quoted line is after the `END OF TERMS AND CONDITIONS` in a section called `APPENDIX: How to apply the Apache License to your work.` which I believe is just there to tell you what you need to do in every file.

And from what I can tell, each file in AHC has the correct information (ie. the placeholders replaced with the real info).

**Comment by 0xTim** [comment]
Hmm maybe you're right, in which case ignore me then!

**Comment by ktoso** [comment]
I think same as @weissi  -- this is just the section of the license that says "this is how you apply it" -- the actual copyright headers in the actual files have the right info.
