### ISSUE TITLE
Suddenly getting "only available in macOS 10.15 or newer" errors

### ISSUE THREAD

**Issue by eob** [swift-server/async-http-client#532]
Hi there,

I awoke today to my Swift project no longer building with the following error from within this package:

```
AsyncHTTPClient/NIOTransportServices/TLSConfiguration.swift:25:35: 
'tls_protocol_version_t' is only available in macOS 10.15 or newer
```

As far as I'm aware, barring MacOS running some update process overnight that mangled things, nothing has changed in my project. Here is what I think is the relevant part of my Package.swift:

```
  platforms: [    .macOS(.v12)   ],
```

I'm on XCode Version 13.2 (13C90).

My guess is that this problem ultimately isn't related to async-http-client, so I feel bad asking on your issue tracker, but even that the error is bubbling up from within this library I wonder if anyone on the project has seen it before and knows the fix?

Thanks!
Ted

**Comment by guillaumekh** [comment]
@eob How did you solve this?
I'm having the same issue, and adding an `@available(macOS 10.15, *)` to circumvent this feels really awkward.

**Comment by jstorm31** [comment]
Same issue for me after upgrading to XCode 13.2.1

**Comment by fabianfett** [comment]
This was an issue in an earlier version of AsyncHTTPClient that was fixed with #411. Please update to at least 1.5.1 to fix the issue.

**Comment by guillaumekh** [comment]
@fabianfett thanks for letting us know. Sorry I missed it in release notes.

@jstorm31 Do you use `soto`? The current stable version of `soto@5.11.0` has a dependency on `soto-core@5.7.0` which has a dependency on `async-http-client@1.3.0`.

I've opened a ticket on soto's tracker: https://github.com/soto-project/soto-core/issues/486

**Comment by jstorm31** [comment]
Thanks for the info. My version of the library was `1.3.0` (some of my other dependencies fixed it to this version). I upgraded to `1.5.1` and it looks fine now. 

I don't use `soto` @guillaumekh
