### ISSUE TITLE
HTTPClient is still using NIOAtomic

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/async-http-client#606]
Given the other NIOAtomics were replaced with ManagedAtomic I assume the HTTPClient one will want to be replaced as well

https://github.com/swift-server/async-http-client/blob/2adca4b0038a7ef81ea0838c5feeda9439c52b64/Sources/AsyncHTTPClient/HTTPClient.swift#L39

**Comment by Lukasa** [comment]
Agreed.

**Comment by Lukasa** [comment]
Looks like this was just an oversight in #603, I'll quickly clean it up.

**Comment by Lukasa** [comment]
Shipped in 1.11.3.
