### ISSUE TITLE
Many sockets in FinWait2 and CloseWait state

### ISSUE THREAD

**Issue by datwelk** [swift-server/async-http-client#674]
When I instantiate many connections (~30 per second) to the same server from iOS, at some point I quickly receive a `connectionFromPoolTimeout` for new connections.

At that point the network profiler shows many sockets in FinWait2 or CloseWait state. When connectivity recovers, the FinWait2 and CloseWait sockets are gone.

Is this an issue on the server side, where the server does not gracefully close connections, or could this be a client side issue? 

I am using the `NIOTSEventLoopGroup`. 

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1571141/226930650-a451a388-1b22-4f69-b7ff-6f0ffd8342c4.png">

**Comment by datwelk** [comment]
The open sockets seem to be unrelated.

I do keep running into the `HTTPClientError.getConnectionFromPoolTimeout` though. I have a minimum reproducible case. The target server doesn't matter.

If you run the sample app, at some point the console will be full of "Failure: HTTPClientError.getConnectionFromPoolTimeout".

https://github.com/datwelk/asynchttpclientsample

**Comment by dnadoba** [comment]
This is expected because you do not have any backpressure. Therefore more request per second get spawned then executed and the queue gets longer and longer. Eventually the requests will timeout and out get `HTTPClientError.getConnectionFromPoolTimeout` as an error.

You can either increase the timeout or limit the number of requests you are doing in parallel.

**Comment by datwelk** [comment]
How could I limit the number of requests in parallel?

**Comment by dnadoba** [comment]
This depends if HTTP/1 or HTTP/2 is used. If HTTP/1 is used the maxHTTP1Connection config says how many requests can run in parallel. If HTTP/2 is used, the server dictates the max parallel requests (called streams in the spec) which can change over time. 

[Something like `TokenBucket` from SwiftPM can be used to limit the maximum requests.](https://github.com/apple/swift-package-manager/blob/main/Sources/Basics/Concurrency/TokenBucket.swift) 

I think at the end we should add some API to allow to easily keep the connection busy without filling up the queue. However, this is not possible today.

**Comment by datwelk** [comment]
Sounds good. I will implement a max req per host limit on my PriorityQueue wrapper. Thank you for your assistance! @dnadoba
