### ISSUE TITLE
Shutdown does not close HTTP2 connection

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/async-http-client#717]
After executing a request via HTTP2 and then calling shutdown the connection to the server is left open. 

I would expect shutdown to close any open connections.

**Comment by natikgadzhi** [comment]
I'm a noob here, but if you have a minimal reproduction snippet, I'd love to try and fix this up.

**Comment by adam-fowler** [comment]
I'm just looking at HTTP2 connections on the server side again. This may be a server issue still

**Comment by adam-fowler** [comment]
Looks like I was mistaken
