### ISSUE TITLE
crashed： free(): corrupted unsorted chunks #2617

### ISSUE THREAD

**Issue by shenfu1991** [swift-server/async-http-client#724]
My Vapor program crashed after receiving several network request errors.

OS: ubuntu20.04
swift version: 5.9.2
async-http-client version: 1.20.0

 http client code:

<pre>
import Vapor
import AsyncHTTPClient

class CoreNetworkingManager {
  
    static let sharedInstance = CoreNetworkingManager()
    var API_Key: String = ""
    
    private let httpClient: HTTPClient
    
    init() {
        httpClient = HTTPClient(eventLoopGroupProvider: .shared(kApp.eventLoopGroup))
    }
    
    // 手动关闭 HTTPClient（通常在应用程序生命周期结束时调用）
    func shutdown() {
        try? httpClient.syncShutdown()
    }
    
    typealias SuccessType = (_ result: Any?, _ data: Data?) -> Void
    typealias CompleteType = (Any) -> Void
    
    func doAsyncWork(method: HTTPMethod, URLString: String, parameters: [String: Any]?, success: SuccessType?, complete: CompleteType?) async {
        var request = HTTPClientRequest(url: URLString)
        request.method = method
        request.headers.add(name: "X-MBX-APIKEY", value: API_Key)
        request.headers.add(name: "Content-Type", value: "application/json")
        
        if let params = parameters, let jsonData = try? JSONSerialization.data(withJSONObject: params) {
            request.body = .bytes(ByteBuffer(data: jsonData))
        }

        do {
            let response = try await httpClient.execute(request, timeout: .seconds(30))
            if response.status == .ok {
                let body = try await response.body.collect(upTo: 1024 * 1024 * 100) // 100 MB
                
                let json = try JSONSerialization.jsonObject(with: Data(buffer: body), options: .allowFragments)
                
                success?(json, Data(buffer: body))
                complete?(json)
            } else {
                complete?("Received error status: \(response.status)")
            }
        } catch let err {
            complete?("Response error: \(err),desc: \(err.localizedDescription)")
        }
    }
    
    func request(method: HTTPMethod, URLString: String, parameters: [String: Any]?, success: SuccessType?, complete: CompleteType?) {
        Task { [weak self] in
            await self?.doAsyncWork(method: method, URLString: URLString, parameters: parameters, success: success, complete: complete)
        }
    }
}

</pre>

part of log:
<pre>
2023-12-30 00:00:44.336 cty_3[244969:68ff9700] 2023-12-30 00:00:44    loadFeatureBalance() 币安接口小黑屋...Received error status: 400 Bad Request    

2023-12-30 00:00:45.314 cty_3[244969:68ff9700] 2023-12-30 00:00:45    loadFeatureBalance() 币安接口小黑屋...Received error status: 400 Bad Request    

2023-12-30 00:00:50.167 cty_3[244969:68ff9700] 2023-12-30 00:00:50    loadFeatureBalance() 币安接口小黑屋...Response error: HTTPClientError.getConnectionFromPoolTimeout,desc: The operation could not be completed. (AsyncHTTPClient.HTTPClientError error 1.)    

2023-12-30 00:00:51.678 cty_3[244969:68ff9700] 2023-12-30 00:00:51    loadFeatureBalance() 币安接口小黑屋...Received error status: 400 Bad Request    

free(): corrupted unsorted chunks

*** Signal 6: Backtracing from 0x7f387c23b00b... done ***

*** Program crashed: Aborted at 0x000000000003bce9 ***

Thread 0 "cty_3":

0  0x00007f387c23b48a <unknown> in libc-2.31.so

Thread 1 "NIO-ELT-0-#0":

0                0x00007f387c31768e <unknown> in libc-2.31.so
1 [ra] [system]  0x0000559f5a48ddb1 specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 624 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
2 [ra] [inlined] 0x0000559f5a48a85a specialized Selector.whenReady(strategy:onLoopBegin:_:) in cty_3 at .build/checkouts/swift-nio/Sources/NIOPosix/SelectorGeneric.swift:288:18
3 [ra]           0x0000559f5a48a85a SelectableEventLoop.run() + 521 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:470:36
4 [ra] [inlined] 0x0000559f5a468d4f static MultiThreadedEventLoopGroup.runTheLoop(thread:parentGroup:canEventLoopBeShutdownIndividually:selectorFactory:initializer:_:) in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:93:22
5 [ra]           0x0000559f5a468d4f closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 334 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:114:41
6 [ra] [thunk]   0x0000559f5a46c433 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 50 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
7 [ra] [thunk]   0x0000559f5a46e95f thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 14 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
8 [ra]           0x0000559f5a4a68fd closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 380 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/ThreadPosix.swift:112:13

Thread 2 "NIO-ELT-0-#1":

0                0x00007f387c31768e <unknown> in libc-2.31.so
1 [ra] [system]  0x0000559f5a48ddb1 specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 624 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
2 [ra] [inlined] 0x0000559f5a48a85a specialized Selector.whenReady(strategy:onLoopBegin:_:) in cty_3 at .build/checkouts/swift-nio/Sources/NIOPosix/SelectorGeneric.swift:288:18
3 [ra]           0x0000559f5a48a85a SelectableEventLoop.run() + 521 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:470:36
4 [ra] [inlined] 0x0000559f5a468d4f static MultiThreadedEventLoopGroup.runTheLoop(thread:parentGroup:canEventLoopBeShutdownIndividually:selectorFactory:initializer:_:) in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:93:22
5 [ra]           0x0000559f5a468d4f closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 334 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:114:41
6 [ra] [thunk]   0x0000559f5a46c433 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 50 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
7 [ra] [thunk]   0x0000559f5a46e95f thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 14 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
8 [ra]           0x0000559f5a4a68fd closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 380 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/ThreadPosix.swift:112:13

Thread 3 "NIO-ELT-0-#2":

0                0x00007f387c31768e <unknown> in libc-2.31.so
1 [ra] [system]  0x0000559f5a48ddb1 specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 624 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
2 [ra] [inlined] 0x0000559f5a48a85a specialized Selector.whenReady(strategy:onLoopBegin:_:) in cty_3 at .build/checkouts/swift-nio/Sources/NIOPosix/SelectorGeneric.swift:288:18
3 [ra]           0x0000559f5a48a85a SelectableEventLoop.run() + 521 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:470:36
4 [ra] [inlined] 0x0000559f5a468d4f static MultiThreadedEventLoopGroup.runTheLoop(thread:parentGroup:canEventLoopBeShutdownIndividually:selectorFactory:initializer:_:) in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:93:22
5 [ra]           0x0000559f5a468d4f closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 334 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:114:41
6 [ra] [thunk]   0x0000559f5a46c433 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 50 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
7 [ra] [thunk]   0x0000559f5a46e95f thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 14 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
8 [ra]           0x0000559f5a4a68fd closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 380 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/ThreadPosix.swift:112:13

Thread 4 "NIO-ELT-0-#3":

0                0x00007f387c31768e <unknown> in libc-2.31.so
1 [ra] [system]  0x0000559f5a48ddb1 specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 624 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
2 [ra] [inlined] 0x0000559f5a48a85a specialized Selector.whenReady(strategy:onLoopBegin:_:) in cty_3 at .build/checkouts/swift-nio/Sources/NIOPosix/SelectorGeneric.swift:288:18
3 [ra]           0x0000559f5a48a85a SelectableEventLoop.run() + 521 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:470:36
4 [ra] [inlined] 0x0000559f5a468d4f static MultiThreadedEventLoopGroup.runTheLoop(thread:parentGroup:canEventLoopBeShutdownIndividually:selectorFactory:initializer:_:) in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:93:22
5 [ra]           0x0000559f5a468d4f closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 334 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:114:41
6 [ra] [thunk]   0x0000559f5a46c433 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 50 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
7 [ra] [thunk]   0x0000559f5a46e95f thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 14 in cty_3 at /root/cty_3/x-bot/<compiler-generated>
8 [ra]           0x0000559f5a4a68fd closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 380 in cty_3 at /root/cty_3/x-bot/.build/checkouts/swift-nio/Sources/NIOPosix/ThreadPosix.swift:112:13

Thread 5 "TP-#0":

0  0x00007f387c622454 do_futex_wait.constprop.0 + 52 in libpthread-2.31.so

Thread 6 "TP-#1":

0  0x00007f387c622454 do_futex_wait.constprop.0 + 52 in libpthread-2.31.so

Thread 7 "TP-#2":

0  0x00007f387c622454 do_futex_wait.constprop.0 + 52 in libpthread-2.31.so

Thread 8 "TP-#3":

0  0x00007f387c622454 do_futex_wait.constprop.0 + 52 in libpthread-2.31.so

Thread 9:

0  0x00007f387c622678 do_futex_wait.constprop.0 + 72 in libpthread-2.31.so

Thread 10:

0  0x00007f387c31768e <unknown> in libc-2.31.so

Thread 11:

0  0x00007f387c622678 do_futex_wait.constprop.0 + 72 in libpthread-2.31.so

Thread 12:

0  0x00007f387c622678 do_futex_wait.constprop.0 + 72 in libpthread-2.31.so

Thread 13 crashed:

0      0x00007f387c23b00b <unknown> in libc-2.31.so
1 [ra] 0x00007f387c28d2fc <unknown> in libc-2.31.so

Thread 14:

0  0x00007f387c622678 do_futex_wait.constprop.0 + 72 in libpthread-2.31.so

Registers:

rax 0x0000000000000000  0
rdx 0x00007f384effd700  00 d7 ff 4e 38 7f 00 00 70 0b 00 3c 38 7f 00 00  ·×ÿN8···p··<8···
rcx 0x00007f387c23b00b  48 8b 84 24 08 01 00 00 64 48 33 04 25 28 00 00  H··$····dH3·%(··
rbx 0x0000000000000000  0
rsi 0x0000000000000002  2
rdi 0x00007f384effc730  07 ea fb 3b fe ff ff ff 00 23 fc 15 8b 94 c6 97  ·êû;þÿÿÿ·#ü···Æ·
rbp 0x00007f384effca80  20 00 00 54 38 7f 00 00 fc d2 28 7c 38 7f 00 00   ··T8···üÒ(|8···
rsp 0x00007f384effc730  07 ea fb 3b fe ff ff ff 00 23 fc 15 8b 94 c6 97  ·êû;þÿÿÿ·#ü···Æ·
 r8 0x0000000000000000  0
 r9 0x00007f384effc730  07 ea fb 3b fe ff ff ff 00 23 fc 15 8b 94 c6 97  ·êû;þÿÿÿ·#ü···Æ·
r10 0x0000000000000008  8
r11 0x0000000000000246  582
r12 0x00007f384effc9a0  10 cb ff 4e 38 7f 00 00 00 57 4e 7d 38 7f 00 00  ·ËÿN8····WN}8···
r13 0x0000000000000010  16
r14 0x00007f387c783000  00 10 00 00 66 72 65 65 28 29 3a 20 63 6f 72 72  ····free(): corr
r15 0x0000000000000001  1
rip 0x00007f387c23b00b  48 8b 84 24 08 01 00 00 64 48 33 04 25 28 00 00  H··$····dH3·%(··

rflags 0x0000000000000246  ZF PF

cs 0x0033  fs 0x0000  gs 0x0000

Images (23 omitted):

0x0000559f59bf0000–0x0000559f5aa436d8 <no build ID>                            cty_3              /root/cty_3/x-bot/.build/x86_64-unknown-linux-gnu/release/cty_3
0x00007f387c1f8000–0x00007f387c391864 eebe5d5f4b608b8a53ec446b63981bba373ca0ca libc-2.31.so       /usr/lib/x86_64-linux-gnu/libc-2.31.so
0x00007f387c610000–0x00007f387c626545 0c044ba611aeeeaebb8374e660061f341ebc0bac libpthread-2.31.so /usr/lib/x86_64-linux-gnu/libpthread-2.31.so

Backtrace took 22.11s

</pre>

loadFeatureBalance()  and  fetchFeatureInstock()

<pre>

func loadFeatureBalance() {
        if isDealloc {
            return
        }
        
        if kIsSimulation {
            DispatchQueue.global().asyncAfter(deadline: .now()+10) {[weak self] in
                self?.loadFeatureBalance()
            }
            return
        }
        
        let timestamp = getTimestamp()
        let paras = [
                     "timestamp": timestamp,
                     "timeInForce": "GTC"
        ]
//        addLog("\(paras)")
        let str = sortWith(paras)
        let signature = str.HMACWith(secret: API_SecretKey)
        let url = "\(fHost)/fapi/v2/balance?\(str)&signature=\(signature)"
        httpTool.request(method: .GET, URLString: url, parameters: nil) {[weak self] result, data in
            guard let self = self else {return}
            if let das = result as? [[String:Any]] {
                das.forEach { dic in
                    let asset = dic["asset"] as? String ?? ""
                    if asset == "USDT" {
                        let balance = Double(dic["balance"] as? String ?? "") ?? 0
                        let availableBalance = Double(dic["availableBalance"] as? String ?? "") ?? 0
                        let crossWalletBalance = Double(dic["crossWalletBalance"] as? String ?? "") ?? 0
                        self.crossWalletBalance = crossWalletBalance
                        self.availableBalance = availableBalance
                        self.balance = balance
                        if self.origialBalance == 2000 {
                            self.origialBalance = self.balance
                            self.shouldWaitUpdate = false
                            self.fetchAssetSuccess = true
                            self.adaptFeatureX()
                        }
                    }
                }
            }
        } complete: { [weak self] res in
            guard let self = self else {return}
            let result = "\(res)"
            if result.contains("error") {
                self.addLog(" \(#function) 币安接口小黑屋...\(result)")
                debugPrint("\(#function) 币安接口小黑屋...")
            }
           
        }
        
        DispatchQueue.global().asyncAfter(deadline: .now()+15) {[weak self] in
            self?.loadFeatureBalance()
        }
        
    }
    
    func fetchFeatureInstock(loop: Bool) {
        if isDealloc {
            return
        }
        
        if kIsSimulation {
            DispatchQueue.global().asyncAfter(deadline: .now()+10) {[weak self] in
                self?.fetchFeatureInstock(loop: loop)
            }
            return
        }
        
        let timestamp = getTimestamp()
        let paras = [
//                     "symbol": kSymbol.uppercased(),
                     "timestamp": timestamp,
                     "recvWindow" : "50000",
        ]
//        addLog("\(paras)")
        let str = sortWith(paras)
        let signature = str.HMACWith(secret: API_SecretKey)
        let url = "\(fHost)/fapi/v2/positionRisk?\(str)&signature=\(signature)"
        httpTool.request(method: .GET, URLString: url, parameters: nil) { [weak self] result, data in
            guard let self = self else {return}
            if let das = result as? [[String:Any]] {
                self.fetchTraderOk = true
                das.forEach { dic in
                    let symbol = dic["symbol"] as? String ?? ""
                    let entryPrice = dic["entryPrice"] as? String ?? ""
                    let positionAmt = dic["positionAmt"] as? String ?? ""
                    if symbol == self.kSymbol.uppercased() {
                        self.stockAvg = Double(entryPrice) ?? 0
                        self.kStock = Double(positionAmt) ?? 0
                    }
                    setStock(symbol: symbol, value: positionAmt)
                }
            }else{
                self.addLog("\(#function):\(result)")
            }
        } complete: { [weak self] res in
            guard let self = self else {return}
            let result = "\(res)"
            if result.contains("error") {
                self.addLog(" \(#function) 币安接口小黑屋...\(result)")
                debugPrint("\(#function) 币安接口小黑屋...")
            }
    
        }
        if loop {
            DispatchQueue.global().asyncAfter(deadline: .now()+15) {[weak self] in
                self?.fetchFeatureInstock(loop: loop)
            }
        }
        
    }

</pre>

**Comment by Lukasa** [comment]
Thanks for filing this issue!

As I said in apple/swift-nio#2617, this appears to be a threading issue in your code. There are quite a few problems even in the code you've used here. I strongly recommend enabling strict concurrency checking in Swift to have the compiler help you, but here are a few:

1. `var API_Key: String = ""` is unsafe. You cannot have mutable state in an object shared across threads.
2. `DispatchQueue.global()` is almost certainly wrong. You are accessing `self` from random threads. As you are assigning to `self` from those threads, this is concurrent mutation of state, which is forbidden in Swift.

You have a lot of code to fix. If you aren't sure where to start, please let me know and I can point you to some useful references.

**Comment by shenfu1991** [comment]
@Lukasa Thank you for your reply. In fact, this is a scheduled task with no concurrent requests. The crash occurs from time to time, so it cannot be reproduced on macOS. I modified the code so that the next network request will be made only after one network request is completed, and it currently works well.

**Comment by Lukasa** [comment]
So while that fix may have appeared to resolve your problem, the bugs fundamentally remain. I strongly recommend using something like the Thread Sanitizer to point at the issues in your code.

**Comment by shenfu1991** [comment]
@Lukasa  Okay, does Xcode have a tool similar to thread detection? Any recommendations for third-party tools would be greatly appreciated.

**Comment by Lukasa** [comment]
You can enable the Thread Sanitizer in your Xcode Scheme settings.
