### ISSUE TITLE
Support for SSE (EventSource)

### ISSUE THREAD

**Issue by koraykoska** [swift-server/async-http-client#728]
I didn't find anything so thought I should ask. Is there any support for EventSource (client side of course)? If not, would it be possible to build something around the existing library without having to support it upstream?

**Comment by czechboy0** [comment]
Hi @koraykoska,

you can build both a client and a server side of SSE using [Swift OpenAPI Generator](https://github.com/apple/swift-openapi-generator), which can use AHC under the hood.

Steps:
1. Clone this example project: https://github.com/apple/swift-openapi-generator/tree/main/Examples/event-streams-client-example
2. Switch the transport from the URLSession transport to the AsyncHTTPClient transport: https://github.com/swift-server/swift-openapi-async-http-client
3. Update the OpenAPI doc to match the service you're connecting to

**Comment by czechboy0** [comment]
More docs on using SSE and other event streams: https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.0/documentation/swift-openapi-generator/useful-openapi-patterns#Event-streams-JSON-Lines-JSON-Sequence-and-Server-sent-Events

**Comment by koraykoska** [comment]
Thank you @czechboy0 ! Just what I was looking for.
