### ISSUE TITLE
OOM if setting `concurrentHTTP1ConnectionsPerHostSoftLimit: .max`

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#751]
I would like to make the pool create as many concurrent connections as possible. So I thought the best way of spelling this is

```
        var httpClientConfig = HTTPClient.Configuration()
        httpClientConfig.connectionPool = .init(
            idleTimeout: .hours(1),
            concurrentHTTP1ConnectionsPerHostSoftLimit: .max
        )
        httpClientConfig.timeout = .init(connect: .seconds(10), read: .seconds(100), write: .seconds(100))
```

unfortunately, the `concurrentHTTP1ConnectionsPerHostSoftLimit: .max` makes AHC OOM even before it creates any connections because `HTTPConnectionPool.HTTP1Connections.init()` preallocates an array of that size.

It shouldn't do that or at least cap it to something reasonable like 1024.

**Comment by natikgadzhi** [comment]
@weissi Do you think it should cap the actual pool size at 1024, or it should pre-initialize the first 1024, but allow making more of the app is actually trying to use more?

I'm not 100% certain but it feels like 1024 _should be enough for any single connection pool?_

**Comment by MahdiBM** [comment]
> or it should pre-initialize the first 1024, but allow making more of the app is actually trying to use more?

That's what which has been implemented.

> I'm not 100% certain but it feels like 1024 should be enough for any single connection pool?

I wouldn't put a relatively arbitrary limit like that. We connect to our own internal services over http and there can be a lot of connections, although I don't think we've reached 1024.
