### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by shenfu1991** [swift-server/async-http-client#792]
My vapor project suddenly crashed when running on Ubuntu 20.04. Here is the crash log:

<pre>
Thread 1 "NIO-SGLTN-0-#0" crashed:

 0              0x00007fc3725e71cf _assertionFailure(_:_:file:line:flags:) + 351 in libswiftCore.so
 1 [ra]         0x00005642ed4f4ff1 IdleWriteStateMachine.requestEndSent() + 176 in App at /root/x-bot-core/.build/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift:668:13
 2 [ra]         0x00005642ec77097e HTTP2ClientRequestHandler.run(_:context:) + 1773 in App at /root/x-bot-core/.build/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift:185:80
 3 [ra]         0x00005642ec773305 HTTP2ClientRequestHandler.sendRequestHead(_:sendEnd:context:) + 1252 in App at /root/x-bot-core/.build/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift:268:14
 4 [ra]         0x00005642ec7705e1 HTTP2ClientRequestHandler.run(_:context:) + 848 in App at /root/x-bot-core/.build/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift:169:18
 5 [ra]         0x00005642ed503371 HTTP2ClientRequestHandler.channelActive(context:) + 576 in App at /root/x-bot-core/.build/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift:88:14
 6 [ra] [thunk] 0x00005642ec774799 protocol witness for _ChannelInboundHandler.channelActive(context:) in conformance HTTP2ClientRequestHandler + 8 in App at //<compiler-generated>
 7 [ra]         0x00005642ecf0b3cf ChannelHandlerContext.invokeChannelActive() + 190 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/ChannelPipeline.swift:1758:28
 8 [ra]         0x00005642ed76fa0c ChannelHandlerContext.fireChannelActive() + 107 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/ChannelPipeline.swift:1579:20
 9 [ra]         0x00005642ed764d61 _ChannelInboundHandler.channelActive(context:) + 48 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/ChannelHandler.swift:284:17
10 [ra] [thunk] 0x00005642ed08e35d protocol witness for _ChannelInboundHandler.channelActive(context:) in conformance HTTP2FramePayloadToHTTP1ClientCodec + 12 in App at //<compiler-generated>
11 [ra]         0x00005642ecf0b3cf ChannelHandlerContext.invokeChannelActive() + 190 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/ChannelPipeline.swift:1758:28
12 [ra]         0x00005642ecf08f0a ChannelPipeline.fireChannelActive0() + 89 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/ChannelPipeline.swift:931:29
13 [ra]         0x00005642ed76baaa ChannelPipeline.fireChannelActive() + 105 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/ChannelPipeline.swift:685:13
14 [ra]         0x00005642ed8bd359 HTTP2StreamChannel.performActivation() + 616 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamChannel.swift:320:23
15 [ra]         0x00005642ed084d08 HTTP2StreamChannel.postInitializerActivate<A>(output:promise:) + 295 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamChannel.swift:288:18
16 [ra]         0x00005642ed8bce08 HTTP2StreamChannel.onInitializationResult<A>(_:promise:) + 279 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamChannel.swift:261:18
17 [ra]         0x00005642ed0856c6 closure #1 in closure #1 in HTTP2StreamChannel.configure(initializer:userPromise:) + 261 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamChannel.swift:224:30
18 [ra]         0x00005642ecf27f91 closure #1 in EventLoopFuture._publicWhenComplete(_:) + 368 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:859:13
19 [ra]         0x00005642ed78f62d EventLoopFuture._addCallback(_:) + 556 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:767:16
20 [ra]         0x00005642ed790210 EventLoopFuture._internalWhenComplete(_:) + 175 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:783:18
21 [ra]         0x00005642ed78f6d4 EventLoopFuture._whenComplete(_:) + 51 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:775:14
22 [ra]         0x00005642ed790548 EventLoopFuture._publicWhenComplete(_:) + 135 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:858:14
23 [ra]         0x00005642ed7904b4 EventLoopFuture.whenComplete(_:) + 51 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:853:14
24 [ra]         0x00005642ed085523 closure #1 in HTTP2StreamChannel.configure(initializer:userPromise:) + 690 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamChannel.swift:223:39
25 [ra]         0x00005642ed085092 HTTP2StreamChannel.getAutoReadFromParent(_:) + 561 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamChannel.swift:275:13
26 [ra]         0x00005642ed8bcf8f HTTP2StreamChannel.configure(initializer:userPromise:) + 318 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamChannel.swift:218:14
27 [ra]         0x00005642ed8cf53d MultiplexerAbstractChannel.configure(initializer:userPromise:) + 92 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/MultiplexerAbstractChannel.swift:124:26
28 [ra]         0x00005642ed89331e HTTP2CommonInboundStreamMultiplexer.createStreamChannel(multiplexer:promise:_:) + 893 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift:370:17
29 [ra]         0x00005642ed08cc12 closure #1 in HTTP2StreamMultiplexer.SendableView.createStreamChannel(promise:_:) + 209 in App at /root/x-bot-core/.build/checkouts/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift:313:69
30 [ra]         0x00005642ed12e644 closure #1 in SelectableEventLoop.run(_:) + 179 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:491:17
31 [ra] [thunk] 0x00005642ed12e764 partial apply for closure #1 in SelectableEventLoop.run(_:) + 19 in App at //<compiler-generated>
32 [ra]         0x00005642ed9433a2 withAutoReleasePool<A>(_:) + 33 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:30:16
33 [ra]         0x00005642ed9462c9 SelectableEventLoop.run(_:) + 104 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:488:9
34 [ra]         0x00005642ed947275 SelectableEventLoop.runLoop(selfIdentifier:) + 1092 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:660:22
35 [ra]         0x00005642ed9475c8 SelectableEventLoop.run() + 695 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:750:33
36 [ra]         0x00005642ed928b0a static MultiThreadedEventLoopGroup.runTheLoop(thread:parentGroup:canEventLoopBeShutdownIndividually:selectorFactory:initializer:metricsDelegate:_:) + 889 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:99:22
37 [ra]         0x00005642ed0f2f0b closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:metricsDelegate:) + 362 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:120:41
38 [ra] [thunk] 0x00005642ed0f5de3 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:metricsDelegate:) + 66 in App at //<compiler-generated>
39 [ra] [thunk] 0x00005642ed148dbf thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 14 in App at //<compiler-generated>
40 [ra]         0x00005642ed149ca0 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 879 in App at /root/x-bot-core/.build/checkouts/swift-nio/Sources/NIOPosix/ThreadPosix.swift:128:17
41 [ra] [thunk] 0x00005642ed149d49 @objc closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 8 in App at //<compiler-generated>

</pre>

**Comment by Lukasa** [comment]
This issue was fixed in 1.22.1 by #768. Please run `swift package update` to update your checkouts, and then re-run.
