### ISSUE TITLE
should we rename `didReceivePart` to `didReceiveBodyPart` ?

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#83]
https://github.com/swift-server/async-http-client/blob/e0eeb0481c0733f7dd6323916c9f4b453ed05be5/Sources/AsyncHTTPClient/HTTPHandler.swift#L322

this is a little unclear, a part of what? I'd say we should rename to `didReceiveBodyPart`

**Comment by ianpartridge** [comment]
Haha I thought about that a while ago but decided "body part" was a bit gruesome 😁

**Comment by weissi** [comment]
> "body part" was a bit gruesome

haha. `RequestBodyPart` / `BodyChunk` (not so great because it might make people think about chunked encoding which isn't necessary for streaming) / smth else?

**Comment by ianpartridge** [comment]
"body part" is the correct terminology so if it helps make the API clearer then maybe we just go with it...
