### ISSUE TITLE
redirects ignore EventLoop preference 

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#88]
@t089 
> Note, that redirects will ignore the preference parameter, won't they?
> 
> https://github.com/swift-server/async-http-client/blob/8fa354df7ccf7139afe4cb9211f17dbcf2c57ed8/Sources/AsyncHTTPClient/HTTPClient.swift#L218

Indeed looks like this part is missing?

_Originally posted by @t089  in https://github.com/swift-server/async-http-client/pull/79#issuecomment-523100808_

**Comment by weissi** [comment]
sorry, I merged the PR because it had 3 accepts. But that's something we need to fix.

**Comment by artemredkin** [comment]
This was solved by #89
